# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 17:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_auto_20161020_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_hire',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
